[tool.poetry]
name = "pg_dump"
version = "0.1.0"
description = ""
authors = ["Rafał Safin <rafal.safin@rafsaf.pl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
croniter = "^1.3.5"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^22.6.0"
coverage = { extras = ["toml"], version = "^6.4.1" }
flake8 = "^4.0.1"
isort = "^5.10.1"
pre-commit = "^2.19.0"
pyupgrade = "^2.37.1"
pytest = "^7.1.2"

[tool.pytest.ini_options]
addopts = "-v"
minversion = "6.0"
testpaths = ["pg_dump"]

[tool.coverage.run]
omit = []
source = ["pg_dupmp"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
