[tool.poetry]
authors = ["Rafał Safin <rafal.safin@rafsaf.pl>"]
description = "A tool for performing scheduled database backups and transferring encrypted data to secure clouds, for home labs, hobby projects, etc., in environments such as k8s, docker, vms."
license = "GNU GPLv3"
name = "backuper"
version = "2.0"

[tool.poetry.dependencies]
croniter = "^1.3.7"
google-cloud-storage = "^2.6.0"
pydantic = "^2.0.2"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
autoflake = "^1.5"
black = "^23.3.0"
coverage = "^7.2.5"
flake8 = "^5.0.4"
freezegun = "^1.2.2"
isort = "^5.12.0"
markdown-include = "^0.8.1"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.21"
mkdocstrings = { extras = ["python"], version = "^0.22.0" }
pre-commit = "^3.2.2"
pyinstaller = { version = "^5.10.1", python = ">=3.11,<3.12" }
pymdown-extensions = "^10.0.1"
pytest = "^7.3.1"
python-dotenv = "^1.0.0"
pyupgrade = "^3.10.1"
responses = "^0.23.1"
watchfiles = "^0.19.0"
mypy = "^1.4.1"
types-croniter = "^1.4.0.0"
types-requests = "^2.31.0.2"
types-google-cloud-ndb = "^2.1.0.7"
bandit = "^1.7.5"

[tool.pytest.ini_options]
addopts = "-v"
filterwarnings = [
  "ignore:Deprecated call to `pkg_resources.declare_namespace\\('google:DeprecationWarning",
  "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
minversion = "6.0"

[tool.coverage.run]
omit = []
source = ["backuper"]

[tool.isort]
profile = "black"

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
skips = ["B404", "B602", "B603"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict = true

[tool.poetry.scripts]
backuper = "backuper.main:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
