[tool.poetry]
authors = ["Rafał Safin <rafal.safin@rafsaf.pl>"]
description = ""
license = "MIT"
name = "backuper"
version = "0.4.0"

[tool.poetry.dependencies]
croniter = "^1.3.7"
google-cloud-storage = "^2.6.0"
pydantic = "^1.10.7"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
autoflake = "^1.5"
black = "^22.6.0"
coverage = { extras = ["toml"], version = "^6.4.1" }
flake8 = "^5.0.4"
freezegun = "^1.2.2"
isort = "^5.12.0"
pre-commit = "^3.2.2"
pytest = "^7.3.1"
python-dotenv = "^1.0.0"
pyupgrade = "^3.3.1"
watchfiles = "^0.19.0"
pyinstaller = { version = "^5.10.1", python = ">=3.11,<3.12" }
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.8"
mkdocstrings = { extras = ["python"], version = "^0.21.2" }
pymdown-extensions = "^9.11"
markdown-include = "^0.8.1"
responses = "^0.23.1"

[tool.pytest.ini_options]
addopts = "-v"
filterwarnings = [
  "ignore:Deprecated call to `pkg_resources.declare_namespace\\('google:DeprecationWarning",
  "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
minversion = "6.0"

[tool.coverage.run]
omit = []
source = ["backuper"]

[tool.isort]
profile = "black"

[tool.poetry.scripts]
backuper = "backuper.main:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
