[tool.poetry]
authors = ["Rafał Safin <rafal.safin@rafsaf.pl>"]
description = ""
license = "MIT"
name = "pg_dump"
version = "0.4.0"

[tool.poetry.dependencies]
python = "^3.11"
croniter = "^1.3.7"
google-cloud-storage = "^2.6.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^0.21.0"
autoflake = "^1.5"
black = "^22.6.0"
coverage = { extras = ["toml"], version = "^6.4.1" }
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest = "^7.2.1"
pyupgrade = "^2.37.3"
watchfiles = "^0.16.1"
freezegun = "^1.2.2"

[tool.pytest.ini_options]
addopts = "-v"
minversion = "6.0"

[tool.coverage.run]
omit = []
source = ["pg_dump"]

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
