[tool.poetry]
authors = ["Rafał Safin <rafal.safin@rafsaf.pl>"]
description = "A tool for performing scheduled database backups and transferring encrypted data to secure clouds, for home labs, hobby projects, etc., in environments such as k8s, docker, vms."
license = "GNU GPLv3"
name = "backuper"
version = "4.0"

[tool.poetry.dependencies]
croniter = "^1.3.7"
google-cloud-storage = "^2.6.0"
pydantic = "^2.2.1"
python = "^3.11"
boto3 = "^1.28.35"
pydantic-settings = "^2.0.3"
azure-storage-blob = "^12.17.0"
azure-identity = "^1.14.0"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2"
black = "^23.7.0"
coverage = "^7.3.0"
flake8 = "^6.1.0"
freezegun = "^1.2.2"
isort = "^5.12.0"
markdown-include = "^0.8.1"
mkdocs = "^1.4.2"
mkdocs-material = "^9.2.5"
mkdocstrings = { extras = ["python"], version = "^0.22.0" }
pre-commit = "^3.2.2"
pyinstaller = { version = "^5.13.1", python = ">=3.11,<3.12" }
pymdown-extensions = "^10.1"
pytest = "^7.3.1"
python-dotenv = "^1.0.0"
pyupgrade = "^3.10.1"
responses = "^0.23.3"
watchfiles = "^0.20.0"
mypy = "^1.5.1"
types-croniter = "^1.4.0.1"
types-requests = "^2.31.0.2"
types-google-cloud-ndb = "^2.2.0.0"
bandit = "^1.7.5"
mike = "^1.1.2"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.3.1"
pytest-env = "^1.0.1"

[tool.pytest.ini_options]
addopts = "-v --cov --cov-report term-missing --cov-fail-under 100 -n auto"
filterwarnings = [
  "ignore:Deprecated call to `pkg_resources.declare_namespace\\('google:DeprecationWarning",
  "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]
env = [
  "SUBPROCESS_TIMEOUT_SECS=5",
  "LOG_LEVEL=DEBUG",
  "BACKUP_MAX_NUMBER=1",
  "BACKUP_PROVIDER=",
  "ZIP_ARCHIVE_PASSWORD=very_unpleasant:password-_-12!@#$%^&*()/;><.,][`~'",
  "LOG_FOLDER_PATH=/tmp/pytest_backuper_env_vars_hook_logs_folder",
]

minversion = "6.0"

[tool.coverage.run]
omit = []
source = ["backuper"]

[tool.isort]
profile = "black"

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
skips = ["B404", "B602", "B603"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict = true

[tool.poetry.scripts]
backuper = "backuper.main:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
